# Generated by Django 3.2.5 on 2021-08-20 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210820_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='page_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='адрес страницы VK'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 13, 51, 56, 299841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=18, verbose_name='возраст'),
        ),
    ]
